### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by gatozee** [azofeifa/FStitch#1]
The program core dumps when I run it on a training set. If you need, I can provide the input files.

**Comment by azofeifa** [comment]
Yes that would be great! Thank you very much!
cheers, Joey

**Comment by gatozee** [comment]
The command I used was:
FStitch -i example.bedgraph -j trainingSet.txt -o example.param

trainingSet.txt and example.bedgraph can be downloaded from
https://www.dropbox.com/sh/cdvq7boepeixvn3/AADniHGetsq9Dm6IarOo7MOda?dl=0

Thank you!

**Comment by azofeifa** [comment]
Hi so I think I found the source of one possible error, although I was
 unable to recapitulate the core-dump I did see that I was not checking for
carriage returns (are you working on a windows machine?), so I fixed that.
At any rate, please re-clone from my github site and run with the -v option
(verbose output) and if the error persists on these input files send me the
standard output. Be sure to recompile.

Thanks very much and I am sorry for this inconvenience.

cheers, Joey

**Comment by gatozee** [comment]
Thank you! I recompiled the new version. But it still core dumped before  -v showed anything. I'm on Linux--just the traningset file is from someone using Windows.

# It compiled successfully:

Compiled main
Compiled BaumWelch
Compiled NewtonsMethod
Compiled read_in_parameters
Compiled read
Compiled main_train
Compiled grabTrainingExamples
Compiled interval_tree
Compiled split
Compiled write
Compiled main_segment
Compiled viterbi

# Compiled validate

Sucessfully Compiled

**Comment by azofeifa** [comment]
interesting! Well, let me look at it again right now and will get back to
you, sorry again for the inconvenience.
cheers, Joey

**Comment by azofeifa** [comment]
So I see in your command

FStitch -i example.bedgraph -j trainingSet.txt -o example.param

that you are missing

"train"

try:

FStitch train -i example.bedgraph -j trainingSet.txt -o example.param

and let me know if you get anymore errors. It still shouldn't be core
dumping sense I check for that but lets see what happens anyway.

cheers, Joey

On Wed, Nov 25, 2015 at 9:56 AM, Joey Azofeifa <joseph.azofeifa@colorado.edu

> wrote:
> 
> interesting! Well, let me look at it again right now and will get back to
> you, sorry again for the inconvenience.
> cheers, Joey
>

**Comment by gatozee** [comment]
Sorry, I did use "train":

FStitch train -v -i example.bedgraph -j trainingSet.txt -o example.param
Segmentation fault (core dumped)

uname -a
Linux k2 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64
x86_64 x86_64 GNU/Linux

**Comment by gatozee** [comment]
BTW, even running the program itself core dumps:

FStitch
please specify either: train or segment
exiting...
Segmentation fault (core dumped)

**Comment by azofeifa** [comment]
okay, I know this is a serious pain, I can't seem to get the error on my
end (tried it on a linux and mac) but I did make some updates that I think
might be the source of the problem for getting a seg fault from just
running the program without anything. Again please re-clone and recompile.

Real quick: what GNU compiler version are you using?

cheers, Joey

**Comment by gatozee** [comment]
gcc 5.2.1

**Comment by azofeifa** [comment]
okay that should be good, this is a fairly annoying process sense I can't
get the error over here, but I appreciate your patience this only helps
make the program more stable, so thanks!

**Comment by gatozee** [comment]
Now it runs without any segfault. Thanks a lot!

**Comment by azofeifa** [comment]
glad it worked out! let me know if anything else comes up!

**Comment by gatozee** [comment]
Can I ask a general question about FStiitch here? Do you recommend creating
a specific training set for each sample or using the training set from one
sample for a batch of samples? Thanks!

**Comment by azofeifa** [comment]
Thats a great question! So in general I would say making a batch training
set is completely reasonable as long as those training examples are
consistent across samples. You wouldn't want a situation where after some
experiment an inactive region becomes an actively transcribed region. So as
long as your training examples are behaving consistently across sample
types than I think it will work fine.
