### ISSUE TITLE
Training exits prematurely

### ISSUE THREAD

**Issue by gatozee** [azofeifa/FStitch#2]
FStitch train exists without writing parameter file. Here's the output:

```
=============================================================
              Fast Read Stitcher Package                     
Last Update: 1/5/2015
Questions? joseph[dot]azofeifa[at]colorado[dot]edu
Running Parameter Estimation

BedGraph File  : sample.min.bedgraph
Training File  : ../trainingSet_minusStrand.txt
Out File       : sample.min.param
Processors     : 8
verbose output : True
=============================================================
reading training file                     : done
making interval tree                      : done
reading bed graph file                    : exiting...
```

**Comment by azofeifa** [comment]
so it looks like it is exiting on trying to read the bed graph file. Have
you tried specifying the full path to sampleminbedgraph ?
cheers, Joey

**Comment by gatozee** [comment]
I tried absolute path, still the same. Didn't FStitch like that file? The bedgraph file was created with bedtools. Can we get more informative error message?

**Comment by azofeifa** [comment]
yeah I am not sure, the bed graph file should be tab delimitated like this

chromosome[\t]start[\t]stop[\t]coverage[\n]

I don't know how bedtools outputs. you could head the first 1000 lines and
I can try running it on my end. If I can figure out the error than I will
write some error messages to catch these use cases!

cheers, Joey

**Comment by gatozee** [comment]
Please see the attached bedgraph file. Thanks!

**Comment by azofeifa** [comment]
I am not sure the file went through, you might just try emailing it to

jgazofeifa@gmail.com

**Comment by azofeifa** [comment]
Okay, I added some additional error messages although I wasn't able to
recover the error on my end, please let me know if it persists.
cheers, Joey

On Tue, Jan 19, 2016 at 1:45 PM, Joey Azofeifa <joseph.azofeifa@colorado.edu

> wrote:
> 
> I am not sure the file went through, you might just try emailing it to
> 
> jgazofeifa@gmail.com
>
