### ISSUE TITLE
Unsure how to use the strand paramater. If I give no strand paramater when segmenting I get only the forward strand. If I used -s neg I get only the forward strand. If I used -s - then it says Unknown user option: -.

### ISSUE THREAD

**Issue by maallen3** [azofeifa/FStitch#3]

**Comment by azofeifa** [comment]
These issues have been resolved. From this point on, there will be no notion of strand, you simply provide an input bedgraph using the -i option to both train and segment FStitch modules. Please let me know of future errors! cheers, Joey
