### ISSUE TITLE
F-stitch Learning rate not converging in C.elegans data

### ISSUE THREAD

**Issue by ghost** [azofeifa/FStitch#4]
I am getting some errors while training on F-stitch.

reading in training file.............................done
inserting bedgraph data to training file intervals...done
transforming data to contig information..............done
running Newton's Method for Logistic Regression......Warning: Learning Algorithm did not converge...
Consider increasing number of maximum iterations...
Warning: Learning Algorithm did not converge...
Consider increasing number of maximum iterations...
Warning: Learning Algorithm did not converge...
Consider increasing number of maximum iterations...
Warning: Learning Algorithm did not converge...
Consider increasing number of maximum iterations...
The files are too big to post to git hub. Let me know if you need more examples.

**Comment by azofeifa** [comment]
Those Warnings will still be in place however you will now receive a parameter.out file (no segmentation fault!). These parameters will correspond to the parameters of the final iterate of newton's method. Adjusting parameters -al, -cm or -reg may lead to more stable runs of Newton's method.  reclone and recompile and let me know if this problem persists. Thanks!

**Comment by ghost** [comment]
Thank you sir! I will keep you posted!

**Comment by ghost** [comment]
I was having trouble running the sh setup.sh. I could not find it in any of
the src directories (there are 2...) instead I modified the make file by
taking the -5 off of the g++ CXX flag. It seemed to compile correctly. Let
me know if you think this will have any effect downstream. Thanks again!
